- package.json
> update remote paths

- package-lock.json
- package.json
- src/index.js
- src/js/modal-lightbox.js
- src/js/modal-movie.js
- src/js/refs.js
- src/sass/components/_modal.scss
- src/templates/card-movie-home.hbs
- src/templates/card-movie-library.hbs
Шаблон карточки фильма Home,
Шаблон карточки фильма My Library,
Изменение слушателя на открытие модального окна с img на карточку фильма
> commit hbs home, library

- src/partials/footer.html
- src/sass/components/_footer.scss
- src/sass/main.scss
adaptive, added heart animation
> Footer without modal

- src/partials/header.html
- src/sass/components/_header.scss
fixed logo, add class search__input to input
> add new class to input

- package-lock.json
- package.json
- src/index.js
- src/partials/header.html
- src/sass/components/_gallery.scss
- src/sass/components/_header.scss
- used animate.css lib to give some life to header elements on page load.
- added hover to movie cards with negative scale and accent-color shadow.
- added some padding to dark theme toggle to place it within header correctly
> added animations and hovers

- src/index.html
- src/index.js
- src/js/refs.js
- src/js/to-top.js
- src/partials/footer.html
- src/sass/base/_reset.scss
- src/sass/components/_footer.scss
> added scroll-to-top button with smooth behaviour

- src/index.js
- src/js/modal-film-lightbox.js
- src/js/refs.js
- src/partials/footer.html
refs в нов формате, добавлен класс модалки на футер
> commit refs

- src/index.js
- src/js/modal-film-lightbox.js
- src/js/modal-team-lightbox.js
- src/partials/library.html
> Refactoring modal

- src/js/apiService.js
- src/js/modal-film-lightbox.js
- src/templates/card-movie.hbs
добавил жанры + картинку для карты фильма в модалке
> add genres and pictures in modal card film

- src/partials/modal.html
- src/sass/components/_button.scss
- src/sass/components/_header.scss
- src/sass/components/_modal-movie.scss
- src/sass/components/_modal.scss
- src/sass/main.scss
- src/templates/card-movie.hbs
- basic visibility for movie modal content
- few hovers here and there
> basic styles for movie modal content visibility

- src/sass/components/_header.scss
> fixed header

- src/sass/components/_modal-movie.scss
> commit modal css

- package-lock.json
- package.json
- src/js/pagination.js
- src/js/search.js
- src/js/startpage.js
- src/partials/library.html
- src/templates/card-movie-home.hbs
добаил недоделанную пагинацию. 
Не обновляет станицу на которой есть.
Поиск работает только 1 запрос 
при переходе в библиотеку и тд (должна пропадать)
по клику на лого cбрасыватся.
> add pagination

- src/js/modal-film-lightbox.js
- src/js/my-library-set-bg-pic.js
- src/js/my-library.js
- src/sass/base/_container.scss
Нужно поменять картинку на что-то приличное в _container.scss
> shows "empty" picture when the Library is empty

- src/js/search.js
- src/js/startpage.js
> add pagination v.2.0

- src/js/pagination.js
- src/sass/components/_pagination.scss
> базовое оформление

- src/sass/components/_modal-movie.scss
> commit css modal movie

- src/sass/components/_modal-movie.scss
> commit css modal

- src/sass/components/_pagination.scss
- src/sass/main.scss
> added paginations styles

- src/index.html
- src/js/modal-film-lightbox.js
- src/sass/components/_trailer-overlay.scss
added the ability to scroll through video trailers for specific movieId
> multiple trailers support

- src/js/filter-movies.js
- src/js/search.js
and put it in the logo adEventList
> added clearFilter func

- src/sass/components/_pagination.scss
> fixed pagination styles
